In [2]:
# 시리즈 연산

# 시리즈 객체 + 연산자(+,-,*,/) + 숫자(스칼라)

dict_data={
    "국어" : 100,
    "영어" : 80,
    "수학" : 90,
}

import pandas as pd

student1 = pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [3]:
percentage  = student1 / 100
print(percentage)

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [4]:
# 시리즈 vs 시리즈

student2 = pd.Series({"수학":80,"국어":90,"영어":80})

print(student1)
print( )
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [5]:
addition =student1 +student2
addition

국어    190
수학    170
영어    160
dtype: int64

In [6]:
subtraction = student1 - student2
subtraction

국어    10
수학    10
영어     0
dtype: int64

In [7]:
multiplication = student1 * student2

multiplication

국어    9000
수학    7200
영어    6400
dtype: int64

In [8]:
divistion = student1 / student2
divistion

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [9]:
result = pd.DataFrame([addition,subtraction,multiplication,divistion], 
            index =["덧셈",'뺄셈',"곱셈","나눗셈"] )

result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [10]:
# Nan 값이 있는 시리즈 연산
import pandas as pd
import numpy as np

student1 = pd.Series({
    "국어" : np.nan,
    "영어": 80 , 
    "수학" : 90
})

student2 = pd. Series({
    "수학": 80,
    "국어":90
})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [11]:

addition = student1 + student2
substraction = student1 - student2
multiplication = student1 * student2
divistion = student1 / student2

print(addition)
print(subtraction)
print(multiplication)
print(divistion)

국어      NaN
수학    170.0
영어      NaN
dtype: float64
국어    10
수학    10
영어     0
dtype: int64
국어       NaN
수학    7200.0
영어       NaN
dtype: float64
국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [12]:
result = pd.DataFrame([
    addition,subtraction,multiplication,divistion
],index=["덧셈",'뺄셈','곱셈','나눗셈'])

result

       국어        수학   영어
덧셈    NaN   170.000  NaN
뺄셈   10.0    10.000  0.0
곱셈    NaN  7200.000  NaN
나눗셈   NaN     1.125  NaN

In [13]:
# 연산 매서드


import pandas as pd
import numpy as np

student1 = pd.Series({
    "국어" : np.nan,
    "영어": 80 , 
    "수학" : 90
})

student2 = pd. Series({
    "수학": 80,
    "국어":90
})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [14]:
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

result = pd.DataFrame([
    sr_add, 
    sr_sub, 
    sr_mul, 
    sr_div
], index=["덧셈", "뺄셈", "곱셈", "나눗셈"])

result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [15]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [1]:
# 데이터프레임의 연산
# 데이터프레임 vs 숫자(스칼라)

import pandas as pd
import seaborn as sns 

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
import os
import certifi

os.environ["SSL_CERT_FILE"] = certifi.where()

In [ ]:
titanic.shape

(891, 15)

In [19]:
titanic.ndim

2

In [20]:
df = titanic.loc[:,["age","fare"]]

In [21]:
# 데이터프레임 vs  데이터 프레임

In [22]:
titanic = sns.load_dataset("titanic")
df = titanic.loc[:,["age","fare"]]

# df. head

In [23]:
addition = df + 10

addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [24]:
substraction = addition - df 
substraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0

In [25]:
import seaborn as sns

# 타이타닉 데이터셋 불러오기
titanic = sns.load_dataset('titanic')

# 잘 불러와졌는지 확인
print(titanic.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [26]:
sample1 = addition.tail()
sample1

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75