In [5]:

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df =titanic.loc[0:9,["age","fare"]]
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [6]:
# 불린 인덱싱

df["age"]<20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [7]:
cond = df["age"]<20
df[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [11]:
df.loc[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [12]:
cond = df["age"]<20
df[~cond]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [13]:
# 나이가 10대인 승객
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [ ]:
(df["age"] >= 10) & (df["age"] < 20)  # and 못 적음!

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: age, dtype: bool

In [19]:
cond = (df["age"] >= 10) & (df["age"] < 20) 
df[cond]

    age     fare
9  14.0  30.0708

In [32]:
cond=(titanic["age"]) >= 10 & (titanic.age < 20)

titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [25]:
cond

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: age, Length: 891, dtype: bool

In [33]:
# 나이가 10세 미만이고 여성인 승객

titanic.head (2)
(titanic["age"] < 10) & titanic["sex"] == f"emale"
titanic[a]

C:\Users\Win11Pro\AppData\Local\Temp\ipykernel_8556\2729147624.py:4: Pandas4Warning: 'and' operations between boolean dtype and str are deprecated and will raise in a future version. Explicitly cast the strings to a boolean dtype before operating instead.
  (titanic["age"] < 10) & titanic["sex"] == f"emale"

NameError: name 'a' is not defined

In [36]:

# 나이가 10세 미만으로 또는 60세 이상인 승객

cond =  (titanic["age"]<10)| (titanic["age"]>=60)
titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
33,0,2,male,66.00,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
851,0,3,male,74.00,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [34]:
titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [39]:
df_under10=titanic.loc[cond , ["age","sex","alone"]]
df_under10

       age     sex  alone
7     2.00    male  False
10    4.00  female  False
16    2.00    male  False
24    8.00  female  False
33   66.00    male   True
..     ...     ...    ...
831   0.83    male  False
850   4.00    male  False
851  74.00    male   True
852   9.00  female  False
869   4.00    male  False

[88 rows x 3 columns]

In [40]:
titanic[["age","sex","alone"]]

      age     sex  alone
0    22.0    male  False
1    38.0  female  False
2    26.0  female   True
3    35.0  female  False
4    35.0    male   True
..    ...     ...    ...
886  27.0    male   True
887  19.0  female   True
888   NaN  female  False
889  26.0    male   True
890  32.0    male   True

[891 rows x 3 columns]

In [41]:
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [67]:
df["age_under_20"] = df["age<=20"]
df

KeyError: 'age<=20'

In [ ]:
#query()매서드 활용
#dataFrame객체. 볃ㄷ교 (조건 문자열)

df =  titanic.

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [46]:
df.query("age<20")

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [63]:
df.query (('age >= 20') or ('fare <q1'))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
6  54.0  51.8625
8  27.0  11.1333

In [66]:
# 나이가 20세 이상 또는 요금이 15달러 이상

a = df .query ("age>10" or 'fare  > 15 ')
a

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
6  54.0  51.8625
8  27.0  11.1333
9  14.0  30.0708

In [56]:
# isin9 매서드 활용

# DataFrame객체 .isin(추출값의 이스트)

pd. set_option("display.max_columns",10)

titanic

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,...,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,...,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [58]:
mask1 = titanic["embark_town"] == "southhamption"
mask2 = titanic["embark_town"] == "Queenston"
df_boolean = titanic[mask1 |mask2]

In [61]:
titanic["embark_town"].isin(["southhampton","Queenstown"])

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890     True
Name: embark_town, Length: 891, dtype: bool