In [2]:
#그룹 객체 만들기
# dataframe객체.groupby(기준이 되는 열)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df =titanic.loc[:,["age","class","sex","fare","survived"]]
df.head()

    age  class     sex     fare  survived
0  22.0  Third    male   7.2500         0
1  38.0  First  female  71.2833         1
2  26.0  Third  female   7.9250         1
3  35.0  First  female  53.1000         1
4  35.0  Third    male   8.0500         0

In [3]:
df['class'].nunique()

3

In [4]:
grouped = df.groupby(["class"],observed=True)
grouped

In [5]:
for key, group in grouped :
    print(key)
    print(group.head())
    print()

('First',)
     age  class     sex     fare  survived
1   38.0  First  female  71.2833         1
3   35.0  First  female  53.1000         1
6   54.0  First    male  51.8625         0
11  58.0  First  female  26.5500         1
23  28.0  First    male  35.5000         1

('Second',)
     age   class     sex     fare  survived
9   14.0  Second  female  30.0708         1
15  55.0  Second  female  16.0000         1
17   NaN  Second    male  13.0000         1
20  35.0  Second    male  26.0000         0
21  34.0  Second    male  13.0000         1

('Third',)
    age  class     sex     fare  survived
0  22.0  Third    male   7.2500         0
2  26.0  Third  female   7.9250         1
4  35.0  Third    male   8.0500         0
5   NaN  Third    male   8.4583         0
7   2.0  Third    male  21.0750         0

In [6]:
average = grouped.mean(numeric_only= True)
average

              age       fare  survived
class
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [7]:
group3 = grouped.get_group(("Third",))
group3

      age  class     sex     fare  survived
0    22.0  Third    male   7.2500         0
2    26.0  Third  female   7.9250         1
4    35.0  Third    male   8.0500         0
5     NaN  Third    male   8.4583         0
7     2.0  Third    male  21.0750         0
..    ...    ...     ...      ...       ...
882  22.0  Third  female  10.5167         0
884  25.0  Third    male   7.0500         0
885  39.0  Third  female  29.1250         0
888   NaN  Third  female  23.4500         0
890  32.0  Third    male   7.7500         0

[491 rows x 5 columns]

In [8]:
# 여러 열을 기준으로 그룹화
grouped_two = df.groupby(["class","sex"])
grouped_two

In [10]:
grouped = df.groupby(["class"])
grouped.std(numeric_only=True)

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [11]:
df.groupby("class").std(numeric_only=True)

              age       fare  survived
class
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

In [12]:
df.groupby(["class"],as_index=False).std(numeric_only=True)

    class        age       fare  survived
0   First  14.802856  78.380373  0.484026
1  Second  14.001077  13.417399  0.500623
2   Third  12.495398  11.778142  0.428949

In [13]:
# grouped = df.groupby("class")
grouped["fare"].std()

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

In [14]:
df.head()

    age  class     sex     fare  survived
0  22.0  Third    male   7.2500         0
1  38.0  First  female  71.2833         1
2  26.0  Third  female   7.9250         1
3  35.0  First  female  53.1000         1
4  35.0  Third    male   8.0500         0

In [15]:
df.groupby("class")["fare"].mean()

class
First     84.154687
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [17]:
df.groupby("class")["fare"].sum()

class
First     18177.4125
Second     3801.8417
Third      6714.6951
Name: fare, dtype: float64

In [23]:
# group객체.aggregate(매핑함수)
# group객체 .agg(매핑함수)

df.groupby("class").aggregate("mean",numeric_only = True)
# df.groupby("class").mean()
df.groupby("class")[["fare","survived"]].aggregate("mean")

             fare  survived
class
First   84.154687  0.629630
Second  20.662183  0.472826
Third   13.675550  0.242363

In [22]:
df.groupby("class")[["fare","survived"]].agg("mean")

             fare  survived
class
First   84.154687  0.629630
Second  20.662183  0.472826
Third   13.675550  0.242363

In [25]:
df.groupby("class").agg(["min","max"])

         age           sex       fare           survived
         min   max     min   max  min       max      min max
class
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

In [27]:
def min_max(x) :
    return x.max() - x.min()

df.groupby("class")[["age","fare"]].agg(min_max)

          age      fare
class
First   79.08  512.3292
Second  69.33   73.5000
Third   73.58   69.5500