In [64]:
import pandas as pd

df = pd.read_csv("./data/auto-mpg.csv",header=None)
df.columns=[
    "mpg","cyliders","displacement","horsepower","weight","acceleration","model year","origin","name"
]

df

,mpg,cyliders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [65]:
mpg_to_kpl = 1.60934 / 3.78541

df["kpl"] = df["mpg"] * mpg_to_kpl

df

,mpg,cyliders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.652571
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.802286
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.227428
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl,11.478857
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup,18.706285
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage,13.604571
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger,11.904000
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10,13.179428

In [66]:
df["kpl"] = df["kpl"].round(2)

df

,mpg,cyliders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl,11.48
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup,18.71
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage,13.60
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger,11.90
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10,13.18

In [67]:
# 자료형 변환

df.dtypes

mpg             float64
cyliders          int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
kpl             float64
dtype: object

In [68]:
df["horsepower"].unique() #데이터가 중복되지 않은 값

# ? <--뭔지는 모르겠지만 replace로 바꾸자함,,

<StringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     '?', '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [69]:
import numpy as np

In [70]:
df["horsepower"] = df["horsepower"].replace("?",np.nan)
df["horsepower"].unique() ## ? --> nan

<StringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     nan, '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [71]:
df = df.dropna(subset=["horsepower"],axis=0)

df

,mpg,cyliders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino,7.23
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl,11.48
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup,18.71
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage,13.60
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger,11.90
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10,13.18

In [72]:
df["horsepower"].unique() # 결측값 삭제

<StringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0', '100.0', '105.0',
 '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00', '76.00',
 '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0', '112.0',
 '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0', '230.0',
 '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
 '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00', '115.0',
 '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0', '68.00',
 '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0', '103.0',
 '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00', '132.0',
 '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 93, dtype: str

In [73]:
df["horsepower"] = df["horsepower"].astype("float")

In [74]:
df.dtypes

mpg             float64
cyliders          int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
kpl             float64
dtype: object

In [75]:
df["origin"].unique()

array([1, 3, 2])

In [76]:
df["origin"].unique

<bound method Series.unique of 0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    2
395    1
396    1
397    1
Name: origin, Length: 392, dtype: int64>

In [77]:
df["origin"].value_counts()

origin
1    245
3     79
2     68
Name: count, dtype: int64

In [78]:
df["origin"]=df["origin"].replace(
    {
        1:"USA",
        2: "EU",
        3: "JAPEN"
    }
)

df["origin"].unique

<bound method Series.unique of 0      USA
1      USA
2      USA
3      USA
4      USA
      ...
393    USA
394     EU
395    USA
396    USA
397    USA
Name: origin, Length: 392, dtype: object>

In [79]:
df["origin"].astype("category")

0      USA
1      USA
2      USA
3      USA
4      USA
      ...
393    USA
394     EU
395    USA
396    USA
397    USA
Name: origin, Length: 392, dtype: category
Categories (3, str): ['EU', 'JAPEN', 'USA']

In [80]:
df.head()

,mpg,cyliders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,USA,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,USA,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,USA,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,USA,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,USA,ford torino,7.23

In [81]:
df["origin"].astype("category")

0      USA
1      USA
2      USA
3      USA
4      USA
      ...
393    USA
394     EU
395    USA
396    USA
397    USA
Name: origin, Length: 392, dtype: category
Categories (3, str): ['EU', 'JAPEN', 'USA']