In [2]:
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [4]:
df.isnull().sum()

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [5]:
# 문자열을 timestamp로 변환

df["Date"]
df["new_date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB

In [7]:
df = df.set_index("new_date")
df = df.drop("Date",axis = 1)

df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [8]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes

In [9]:
pd.DatetimeIndex([
    "2022-12-15","2023/01/25"
])

DatetimeIndex(['2022-12-15', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [10]:
pd.DatetimeIndex([
    "1040"
])

DatetimeIndex(['1040-01-01'], dtype='datetime64[us]', freq=None)

In [11]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [12]:
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [13]:
# pd.Timestamp("2023:12:25")

In [14]:
pd.to_datetime("2025년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2025-12-25 00:00:00')

In [15]:
# pd.to_datetime("12-12-2023 23:29:29",format(%d - %m -%Y%    ))

In [16]:
pd.to_datetime("2025:12:25", format="%Y:%m:%d")

Timestamp('2025-12-25 00:00:00')

In [17]:
pd.to_datetime("05-12-23 23:59:59", format="%d-%m-%y %H:%M:%S")

Timestamp('2023-12-05 23:59:59')

In [18]:
# timestamp를 이용해서 period로 변환

dates = ["2019-01-01","2020-03-01","2021-06-01"]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [19]:
pr_day = ts_dates.to_period(freq="D")
pr_day

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [20]:
pr_month=ts_dates.to_period(freq = "M")
pr_month

PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')

In [21]:
pr_year=ts_dates.to_period(freq = "Y")
pr_year

PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [22]:
#시계열 데이터 만들기
#월 시작일 기준
ts_ms = pd.date_range(
    start = "2024-01-01",
    end=None,
    periods=6,
    freq="MS",
    tz='Asia/Seoul'
)

ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [23]:
# 월 막말 기준
ts_me = pd.date_range(
    start = "2024-01-01",
    end=None,
    periods=6,
    freq="ME",
    tz='Asia/Seoul'
)

ts_me

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [24]:
# 분기(3개월)간격
ts_3m = pd.date_range(
    start = "2024-01-01",
    periods=6,
    freq="3MS",
    tz='Asia/Seoul'
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [25]:
# 시계열 데이터 활용

df = pd.read_csv("./data/stock-data.csv")
df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [26]:
df["new_Date"]= pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [27]:
df["new_Date"]

0    2018-07-02
1    2018-06-29
2    2018-06-28
3    2018-06-27
4    2018-06-26
5    2018-06-25
6    2018-06-22
7    2018-06-21
8    2018-06-20
9    2018-06-19
10   2018-06-18
11   2018-06-15
12   2018-06-14
13   2018-06-12
14   2018-06-11
15   2018-06-08
16   2018-06-07
17   2018-06-05
18   2018-06-04
19   2018-06-01
Name: new_Date, dtype: datetime64[us]

In [28]:
df["year"] = df["new_Date"].dt.year

In [29]:
df["month"] = df["new_Date"].dt.month

In [30]:
df["day"] = df["new_Date"].dt.day

In [31]:
df.head()

         Date  Close  Start   High    Low  Volume   new_Date  year  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [32]:
df["Date_yr"] = df["new_Date"].dt.to_period(freq="Y")

In [33]:
df["Date_mo"] = df["new_Date"].dt.to_period(freq="M")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
 7   year      20 non-null     int32
 8   month     20 non-null     int32
 9   day       20 non-null     int32
 10  Date_yr   20 non-null     period[Y-DEC]
 11  Date_mo   20 non-null     period[M]
dtypes: datetime64[us](1), int32(3), int64(5), period[M](1), period[Y-DEC](1), str(1)
memory usage: 1.8 KB

In [34]:
##다 다른 Dtype에 집중

In [35]:
# 시간인덱스 활용
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")
df["new_Date"] = pd.to_datetime(df["Date"])

df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [36]:
df = df.set_index("new_Date")
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [37]:
df = df.sort_index() # sort_values()

df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [38]:
df.loc["2018-06-27"]

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [39]:
df.loc["2018-06-27":"2018-07-02"]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [40]:
cond = df.index < "2018-06-05"

cond

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [41]:
df[cond]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [42]:
pd.Timestamp("2018-06-27")

Timestamp('2018-06-27 00:00:00')

In [43]:
pd.Timestamp(2018, 6, 27)

Timestamp('2018-06-27 00:00:00')

In [44]:
df.loc[pd.Timestamp(2018, 6, 27) : pd.Timestamp(2018,7,2)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [45]:
df.loc[
    pd.Timestamp(2018, 6, 27, 10, 30, 0):pd.Timestamp(2018, 7, 2, 23, 59, 59)
]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [46]:
# timedelta

print(pd.Timedelta("1 days"))
print(pd.Timedelta(days=1))
print(pd.Timedelta("1 days 1 hours 1 minutes 1 seconds"))
print(pd.Timedelta(days =1,hours =1 , minutes =1 , seconds =1))

1 days 00:00:00
1 days 00:00:00
1 days 01:01:01
1 days 01:01:01

In [47]:
df. head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [48]:
a = df.index
a

DatetimeIndex(['2018-06-01', '2018-06-04', '2018-06-05', '2018-06-07',
               '2018-06-08', '2018-06-11', '2018-06-12', '2018-06-14',
               '2018-06-15', '2018-06-18', '2018-06-19', '2018-06-20',
               '2018-06-21', '2018-06-22', '2018-06-25', '2018-06-26',
               '2018-06-27', '2018-06-28', '2018-06-29', '2018-07-02'],
              dtype='datetime64[us]', name='new_Date', freq=None)

In [49]:
b = pd.Timestamp("2018-07-03") - a
b

TimedeltaIndex(['32 days', '29 days', '28 days', '26 days', '25 days',
                '22 days', '21 days', '19 days', '18 days', '15 days',
                '14 days', '13 days', '12 days', '11 days',  '8 days',
                 '7 days',  '6 days',  '5 days',  '4 days',  '1 days'],
               dtype='timedelta64[us]', name='new_Date', freq=None)

In [50]:
c = a + pd.Timedelta(days=1)
c

DatetimeIndex(['2018-06-02', '2018-06-05', '2018-06-06', '2018-06-08',
               '2018-06-09', '2018-06-12', '2018-06-13', '2018-06-15',
               '2018-06-16', '2018-06-19', '2018-06-20', '2018-06-21',
               '2018-06-22', '2018-06-23', '2018-06-26', '2018-06-27',
               '2018-06-28', '2018-06-29', '2018-06-30', '2018-07-03'],
              dtype='datetime64[us]', name='new_Date', freq=None)

In [51]:
c.min()

Timestamp('2018-06-02 00:00:00')

In [52]:
c.max()

Timestamp('2018-07-03 00:00:00')

In [56]:
# 시계열 변환
df = pd.read_csv("./data/stock-data.csv")


df["new_Date"] = pd.to_datetime(df["Date"])

df = df.drop(columns=["Date"])

df = df.set_index("new_Date").sort_index()

ts = df.head(10)

ts

            Close  Start   High    Low  Volume
new_Date
2018-06-01  11900  11800  12100  11750   32062
2018-06-04  11900  11900  12200  11700   25171
2018-06-05  12150  11800  12250  11800   42485
2018-06-07  11950  12200  12300  11900   49088
2018-06-08  11950  11950  12200  11800   59258
2018-06-11  11950  12000  12250  11950   62293
2018-06-12  13200  12200  13300  12050  558148
2018-06-14  13450  13200  13700  13150  347451
2018-06-15  13400  13600  13600  12900  201376
2018-06-18  12000  13400  13400  12000  309787

In [ ]:
ts.shift(3, freq="D") #인덱스 값이 3일씩 미루어짐

            Close  Start   High    Low  Volume
new_Date
2018-06-04  11900  11800  12100  11750   32062
2018-06-07  11900  11900  12200  11700   25171
2018-06-08  12150  11800  12250  11800   42485
2018-06-10  11950  12200  12300  11900   49088
2018-06-11  11950  11950  12200  11800   59258
2018-06-14  11950  12000  12250  11950   62293
2018-06-15  13200  12200  13300  12050  558148
2018-06-17  13450  13200  13700  13150  347451
2018-06-18  13400  13600  13600  12900  201376
2018-06-21  12000  13400  13400  12000  309787